<a href="https://colab.research.google.com/github/kevinNdyabandiho/-googlecolab/blob/master/NN(perceptron).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
targets = np.array([0, 1, 1, 0])

#### OOP

In [3]:
class Perceptron:
    def __init__ (self, num_inputs, lr = 0.1):
        self.weights = np.zeros(num_inputs)
        self.bias = 0
        self.lr = lr

    def predict(self, inputs):
        weighted_sum = np.dot(inputs, self.weights) + self.bias
        output = 1 if weighted_sum > 0 else 0
        return output

In [4]:
perceptron = Perceptron(num_inputs = 2, lr = 0.1)

In [5]:
for _ in range(100):
    for input_data, target in zip(inputs, targets):
        pred = perceptron.predict(input_data)
        error = target - pred
        perceptron.weights += perceptron.lr * error * input_data
        perceptron.bias += perceptron.lr * error

In [6]:
print("inputs\t\toutput")     # 0, 1, 1, 0
for input_data in inputs:
    prediction = perceptron.predict(input_data)
    print(f"{input_data}\t\t{prediction}")

inputs		output
[0 0]		1
[0 1]		1
[1 0]		0
[1 1]		0


#### MLP (LSTM)

In [8]:
from keras.engine.training import optimizer

inputs = np.reshape(inputs, (inputs.shape[0], inputs.shape[1], 1))

mlp = tf.keras.Sequential([
    tf.keras.layers.LSTM(units = 4, input_shape = (2, 1)),
    tf.keras.layers.Dense(units = 1, activation='sigmoid')
])

mlp.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

mlp.fit(inputs, targets, epochs = 1000, verbose = 0)

In [9]:
pred = mlp.predict(inputs)
pred = np.round(pred).flatten()

1/1 [==============================] - 0s 452ms/step


In [10]:
print("Input \t\tOutput")
for input_data, pred_o in zip(inputs, pred):
    print(f"{input_data}\t\t{int(pred_o)}")

Input 		Output
[[0]
 [0]]		0
[[0]
 [1]]		1
[[1]
 [0]]		1
[[1]
 [1]]		0
